#!/bin/bash

# Prevent spelling accidents when creating commits to be deployed
# by teamcity

if [ "$CREATE_DEPLOYMENT" != "true" ]; then
   exit 0;
fi

COMMIT_MSG_FILE=$1
function do_tc_init {
    exec < /dev/tty

    printf "Enable teamcity for this project? [Y/n]\n"
    read enable_tc

    if [ "$enable_tc" == "Y" ]; then
        init_teamcity_project
        prompt_user
    else
        no_teamcity_project
    fi
}

function prompt_user {
    printf "----------"
    printf "Would you like to trigger a for this commit?\n[Y/n]: "
    read autodeploy

    if [ "$autodeploy" == "Y" ]; then
        echo $1
        echo ":autodeploy" >> $COMMIT_MSG_FILE
    fi

    printf "Enter bugs fixed: "
    read bugs_fixed

    echo ":fixes-bugs" $bugs_fixed >> $COMMIT_MSG_FILE
}

function init_teamcity_project {
    echo "enabled" > ./.git/hooks/.teamcityproj
}

function no_teamcity_project {
    echo "disabled" > ./.git/hooks/.teamcityproj
}


if [ -f ".git/hooks/.teamcityproj" ]; then
    tc_enabled=$(cat ./.git/hooks/.teamcityproj)
    if [ "$tc_enabled" == "enabled" ]; then
        exec < /dev/tty
        prompt_user
    fi
else
    do_tc_init
fi

